# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."
# toolchain = "nightly-2022-08-01"
# docker_image = "thewawar/ckb-capsule:2022-08-01"

# capsule version
version = "0.10.0"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "ckb-combine-lock"
template_type = "Rust"

[[contracts]]
name = "child-script-example"
template_type = "Rust"

[[contracts]]
name = "child-script-always-success"
template_type = "Rust"

[[contracts]]
name = "auth-script-test"
template_type = "Rust"

[[contracts]]
name = "global-registry"
template_type = "Rust"

[[contracts]]
name = "child-script-always-failure"
template_type = "Rust"
